In [1]:
import numpy as np

<h1>Data types and attributes</h1>

In [2]:
#numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2.0, 3.3],
               [4,5, 6.5]])

a3 = np.array([[[1,2,3], 
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [16]:
# creating numpy arrays with 1 where-in  we mention the shape
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#similarly creating numpy arrays filled with zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# creating numpy array with range of values
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
# creating array with randomly generated values
# the below creates an array of size =3,5 where the range of random values is between low(0 here ) 
# high (10 here ) . its to be noted that the generated values will be low inclusive and high exclusive
random_array = np.random.randint(0,10, size=(3,5))
random_array                                 

array([[1, 7, 7, 2, 9],
       [5, 4, 4, 6, 0],
       [0, 3, 8, 5, 9]])

In [28]:
#another way of creating random array
# note that here we not passing any range for random values , but passing only the size
# also note that in this case it comes up with float values
random_array2 = np.random.random((5,3))
random_array2

array([[0.43190306, 0.49053714, 0.15369336],
       [0.88991384, 0.93671871, 0.66554535],
       [0.70327899, 0.95394901, 0.25885596],
       [0.01040778, 0.36604011, 0.14662108],
       [0.06799695, 0.47546925, 0.34814169]])

In [31]:
# another alternate way of doing the previous is as follows
random_array3 = np.random.rand(5,3)
random_array3

array([[0.36150437, 0.48736534, 0.79015782],
       [0.63995111, 0.29752006, 0.27528889],
       [0.44372903, 0.98066187, 0.29363768],
       [0.86455715, 0.45039862, 0.52820095],
       [0.79439748, 0.73508833, 0.51531014]])

<h4>getting the dimensions of a numpy array</h4>

In [7]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

<h4>getting the datatype</h4>

In [8]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

<h4>getting the size</h4>

In [11]:
# size tells us how many elements we have got in the array
a1.size , a2.size , a3.size

(3, 6, 18)

<h4>getting the shape</h4>

In [24]:
# getting shape of ndarray
a1.shape, a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

<h1>creating pandas dataframe from numpy array</h1>

In [14]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5