In [1]:
import numpy as np

<h1>Data types and attributes</h1>

In [2]:
#numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0, 3.3],
               [4,5, 6.5]])

a3 = np.array([[[1,2,3], 
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
# creating numpy arrays with 1 where-in  we mention the shape
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#similarly creating numpy arrays filled with zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# creating numpy array with range of values
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [8]:
# creating array with randomly generated values
# the below creates an array of size =3,5 where the range of random values is between low(0 here ) 
# high (10 here ) . its to be noted that the generated values will be low inclusive and high exclusive
random_array = np.random.randint(0,10, size=(3,5))
random_array                                 

array([[0, 2, 1, 8, 0],
       [3, 7, 7, 7, 2],
       [8, 8, 1, 6, 3]])

In [9]:
#another way of creating random array
# note that here we not passing any range for random values , but passing only the size
# also note that in this case it comes up with float values
random_array2 = np.random.random((5,3))
random_array2

array([[0.96995641, 0.59275372, 0.89594137],
       [0.8175869 , 0.71180846, 0.40778609],
       [0.14712337, 0.46002654, 0.09937011],
       [0.42021329, 0.31838156, 0.57013693],
       [0.07437596, 0.15887358, 0.11041563]])

In [10]:
# another alternate way of doing the previous is as follows
random_array3 = np.random.rand(5,3)
random_array3

array([[0.70042498, 0.87588091, 0.51108921],
       [0.62554304, 0.53394703, 0.95082794],
       [0.12248539, 0.08689098, 0.03025991],
       [0.49764731, 0.92133796, 0.25381389],
       [0.96148047, 0.16589339, 0.32770524]])

In [11]:
# it is to be noted that everytime we initialize random_array3 it is filled with different
# it is filled with different set of values  however if we set the seed to a fixed value then
# fixed set of random numbers will be generated based upon the seed
np.random.seed(10)
random_array4 = np.random.rand(5,3)
random_array4

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096]])

<h4>getting the dimensions of a numpy array</h4>

In [12]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

<h4>getting the datatype</h4>

In [13]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

<h4>getting the size</h4>

In [14]:
# size tells us how many elements we have got in the array
a1.size , a2.size , a3.size

(3, 6, 18)

<h4>getting the shape</h4>

In [15]:
# getting shape of ndarray
a1.shape, a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

<h1>creating pandas dataframe from numpy array</h1>

In [16]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

<h1> viewing arrays and matrices</h1>

In [17]:
# finding all unique numbers
np.random.seed(seed=100)
random_array_4 = np.random.randint(10, size=(5,3))
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [18]:
a1

array([1, 2, 3])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
a1[0]

1

In [22]:
a2[0]

array([1. , 2. , 3.3])

In [23]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#we can also apply slicing to select only a fixed set of elements
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [25]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 0, 9, 6, 2],
         [4, 1, 5, 3, 4],
         [4, 3, 7, 1, 1],
         [7, 7, 0, 2, 9]],

        [[9, 3, 2, 5, 8],
         [1, 0, 7, 6, 2],
         [0, 8, 2, 5, 1],
         [8, 1, 5, 4, 2]],

        [[8, 3, 5, 0, 9],
         [3, 6, 3, 4, 7],
         [6, 3, 9, 0, 4],
         [4, 5, 7, 6, 6]]],


       [[[2, 4, 2, 7, 1],
         [6, 6, 0, 7, 2],
         [3, 5, 4, 2, 4],
         [3, 7, 9, 0, 0]],

        [[5, 9, 6, 6, 5],
         [6, 4, 7, 3, 9],
         [2, 3, 8, 7, 1],
         [5, 9, 3, 0, 6]],

        [[2, 3, 4, 8, 9],
         [8, 5, 2, 7, 5],
         [9, 0, 9, 8, 6],
         [2, 0, 5, 3, 2]]]])

In [26]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [27]:
#get the first 4 numbers of the the inner most arrays
a4[:, :, :, :4]

array([[[[4, 0, 9, 6],
         [4, 1, 5, 3],
         [4, 3, 7, 1],
         [7, 7, 0, 2]],

        [[9, 3, 2, 5],
         [1, 0, 7, 6],
         [0, 8, 2, 5],
         [8, 1, 5, 4]],

        [[8, 3, 5, 0],
         [3, 6, 3, 4],
         [6, 3, 9, 0],
         [4, 5, 7, 6]]],


       [[[2, 4, 2, 7],
         [6, 6, 0, 7],
         [3, 5, 4, 2],
         [3, 7, 9, 0]],

        [[5, 9, 6, 6],
         [6, 4, 7, 3],
         [2, 3, 8, 7],
         [5, 9, 3, 0]],

        [[2, 3, 4, 8],
         [8, 5, 2, 7],
         [9, 0, 9, 8],
         [2, 0, 5, 3]]]])

<h1> manipulating and comparing arrays</h1>

### Arithmatic

In [28]:
a1

array([1, 2, 3])

In [29]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [30]:
#addition
a1 + ones

array([2., 3., 4.])

In [31]:
#subtraction
a1 - ones

array([0., 1., 2.])

In [32]:
#multiplication
a1 * ones

array([1., 2., 3.])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [35]:
# however uncommenting the below will give error since the dimensions are not compatible
# search-  how to reshape numpy array
# a2 * a3

In [36]:
## division 
a1 / ones

array([1., 2., 3.])

In [37]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [38]:
## floor division removes the dcimals [rounds down]
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [39]:
# power 
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [40]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [41]:
# to do modular division 
a1 % 2

array([1, 0, 1], dtype=int32)

In [42]:
# to get exponential
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [43]:
# to get the log value
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

aggregation = performing the same operation on a number of things

In [44]:
#using python function to do sum
sum(a1)

6

In [45]:
#using numpy function to do the sum
np.sum(a1)

6

In [46]:
#though both does the same . but the difference in performce is visibible for larger dataset
# creating a massicve numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [47]:
%timeit sum(massive_array) #using python's sum
%timeit np.sum(massive_array) #numpy's sum
# thus the numpy sum is way more faster

4.41 ms ± 8.98 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
16.1 μs ± 496 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [48]:
### finding mean 
np.mean(a2)

3.6333333333333333

In [49]:
## find max
np.max(a2)

6.5

In [50]:
# finding min
np.min(a2)

1.0

In [51]:
# finding stardard deviation
# standard deviation = a measure of how spread out a group of number is from the mean
np.std(a2)

1.8226964152656422

In [52]:
# finding variance
# variance = meansure of the average degree to which each number is different to the mean
# higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [53]:
# standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

### Reshape and transpose

In [54]:
# the below line if uncommented gives error since they could not be broadcast together
# i.e. when operating on two arrays , Numpy compares their shapes element-wise . its starts 
# with the trailing dimensions, and works its way forward.k Two dimensions are compatible when
#   1. they are equal or 
#   2. one of them is 1

# a2 * a3

In [55]:
a2.shape , a3.shape

((2, 3), (2, 3, 3))

In [56]:
# in order to do mulitplication between these two we have reshape a2. 
# this is done as shown below 
a2.reshape(2,3,1).shape

(2, 3, 1)

In [57]:
# thus to do multiplication 
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [58]:
## transpose 
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
# we can do transpose the matrix as shown below 
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [60]:
a2.shape , a2.T.shape

((2, 3), (3, 2))

<h1>Dot product</h1>