In [1]:
import numpy as np

<h1>1. Data types and attributes</h1>

In [2]:
#numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0, 3.3],
               [4,5, 6.5]])

a3 = np.array([[[1,2,3], 
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
# creating numpy arrays with 1 where-in  we mention the shape
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#similarly creating numpy arrays filled with zeros
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# creating numpy array with range of values
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [8]:
# creating array with randomly generated values
# the below creates an array of size =3,5 where the range of random values is between low(0 here ) 
# high (10 here ) . its to be noted that the generated values will be low inclusive and high exclusive
random_array = np.random.randint(0,10, size=(3,5))
random_array                                 

array([[6, 9, 5, 4, 5],
       [4, 0, 8, 8, 7],
       [6, 4, 4, 8, 8]])

In [9]:
#another way of creating random array
# note that here we not passing any range for random values , but passing only the size
# also note that in this case it comes up with float values
random_array2 = np.random.random((5,3))
random_array2

array([[0.09407375, 0.44810896, 0.57961815],
       [0.35511782, 0.21975659, 0.83233136],
       [0.51170226, 0.69877978, 0.27390783],
       [0.277895  , 0.853965  , 0.59028642],
       [0.79188148, 0.5275953 , 0.29135222]])

In [10]:
# another alternate way of doing the previous is as follows
random_array3 = np.random.rand(5,3)
random_array3

array([[0.31494284, 0.16540656, 0.22210604],
       [0.03816803, 0.78796187, 0.33549885],
       [0.27153204, 0.17500053, 0.95793835],
       [0.4556363 , 0.3777763 , 0.83126157],
       [0.54204125, 0.53383779, 0.50565233]])

In [11]:
# it is to be noted that everytime we initialize random_array3 it is filled with different
# it is filled with different set of values  however if we set the seed to a fixed value then
# fixed set of random numbers will be generated based upon the seed
np.random.seed(10)
random_array4 = np.random.rand(5,3)
random_array4

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084],
       [0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096]])

<h4>getting the dimensions of a numpy array</h4>

In [12]:
a1.ndim , a2.ndim , a3.ndim

(1, 2, 3)

<h4>getting the datatype</h4>

In [13]:
a1.dtype , a2.dtype , a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

<h4>getting the size</h4>

In [14]:
# size tells us how many elements we have got in the array
a1.size , a2.size , a3.size

(3, 6, 18)

<h4>getting the shape</h4>

In [15]:
# getting shape of ndarray
a1.shape, a2.shape , a3.shape

((3,), (2, 3), (2, 3, 3))

<h1>2. creating pandas dataframe from numpy array</h1>

In [16]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

<h1>3. viewing arrays and matrices</h1>

In [17]:
# finding all unique numbers
np.random.seed(seed=100)
random_array_4 = np.random.randint(10, size=(5,3))
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 7, 8])

In [18]:
a1

array([1, 2, 3])

In [19]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [20]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
a1[0]

1

In [22]:
a2[0]

array([1. , 2. , 3.3])

In [23]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
#we can also apply slicing to select only a fixed set of elements
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [25]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 0, 9, 6, 2],
         [4, 1, 5, 3, 4],
         [4, 3, 7, 1, 1],
         [7, 7, 0, 2, 9]],

        [[9, 3, 2, 5, 8],
         [1, 0, 7, 6, 2],
         [0, 8, 2, 5, 1],
         [8, 1, 5, 4, 2]],

        [[8, 3, 5, 0, 9],
         [3, 6, 3, 4, 7],
         [6, 3, 9, 0, 4],
         [4, 5, 7, 6, 6]]],


       [[[2, 4, 2, 7, 1],
         [6, 6, 0, 7, 2],
         [3, 5, 4, 2, 4],
         [3, 7, 9, 0, 0]],

        [[5, 9, 6, 6, 5],
         [6, 4, 7, 3, 9],
         [2, 3, 8, 7, 1],
         [5, 9, 3, 0, 6]],

        [[2, 3, 4, 8, 9],
         [8, 5, 2, 7, 5],
         [9, 0, 9, 8, 6],
         [2, 0, 5, 3, 2]]]])

In [26]:
a4.shape , a4.ndim

((2, 3, 4, 5), 4)

In [27]:
#get the first 4 numbers of the the inner most arrays
a4[:, :, :, :4]

array([[[[4, 0, 9, 6],
         [4, 1, 5, 3],
         [4, 3, 7, 1],
         [7, 7, 0, 2]],

        [[9, 3, 2, 5],
         [1, 0, 7, 6],
         [0, 8, 2, 5],
         [8, 1, 5, 4]],

        [[8, 3, 5, 0],
         [3, 6, 3, 4],
         [6, 3, 9, 0],
         [4, 5, 7, 6]]],


       [[[2, 4, 2, 7],
         [6, 6, 0, 7],
         [3, 5, 4, 2],
         [3, 7, 9, 0]],

        [[5, 9, 6, 6],
         [6, 4, 7, 3],
         [2, 3, 8, 7],
         [5, 9, 3, 0]],

        [[2, 3, 4, 8],
         [8, 5, 2, 7],
         [9, 0, 9, 8],
         [2, 0, 5, 3]]]])

<h1>4. manipulating and comparing arrays</h1>

### Arithmatic

In [28]:
a1

array([1, 2, 3])

In [29]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [30]:
#addition
a1 + ones

array([2., 3., 4.])

In [31]:
#subtraction
a1 - ones

array([0., 1., 2.])

In [32]:
#multiplication
a1 * ones

array([1., 2., 3.])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [35]:
# however uncommenting the below will give error since the dimensions are not compatible
# search-  how to reshape numpy array
# a2 * a3

In [36]:
## division 
a1 / ones

array([1., 2., 3.])

In [37]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [38]:
## floor division removes the dcimals [rounds down]
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [39]:
# power 
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [40]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [41]:
# to do modular division 
a1 % 2

array([1, 0, 1], dtype=int32)

In [42]:
# to get exponential
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [43]:
# to get the log value
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

aggregation = performing the same operation on a number of things

In [44]:
#using python function to do sum
sum(a1)

6

In [45]:
#using numpy function to do the sum
np.sum(a1)

6

In [46]:
#though both does the same . but the difference in performce is visibible for larger dataset
# creating a massicve numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [47]:
%timeit sum(massive_array) #using python's sum
%timeit np.sum(massive_array) #numpy's sum
# thus the numpy sum is way more faster

4.86 ms ± 825 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
33 μs ± 56.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
### finding mean 
np.mean(a2)

3.6333333333333333

In [49]:
## find max
np.max(a2)

6.5

In [50]:
# finding min
np.min(a2)

1.0

In [51]:
# finding stardard deviation
# standard deviation = a measure of how spread out a group of number is from the mean
np.std(a2)

1.8226964152656422

In [52]:
# finding variance
# variance = meansure of the average degree to which each number is different to the mean
# higher variance = wider range of numbers
# lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [53]:
# standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

### Reshape and transpose

In [54]:
# the below line if uncommented gives error since they could not be broadcast together
# i.e. when operating on two arrays , Numpy compares their shapes element-wise . its starts 
# with the trailing dimensions, and works its way forward.k Two dimensions are compatible when
#   1. they are equal or 
#   2. one of them is 1

# a2 * a3

In [55]:
a2.shape , a3.shape

((2, 3), (2, 3, 3))

In [56]:
# in order to do mulitplication between these two we have reshape a2. 
# this is done as shown below 
a2.reshape(2,3,1).shape

(2, 3, 1)

In [57]:
# thus to do multiplication 
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [58]:
## transpose 
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [59]:
# we can do transpose the matrix as shown below 
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [60]:
a2.shape , a2.T.shape

((2, 3), (3, 2))

<h1>5. Dot product</h1>

In [61]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))

In [62]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [63]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [64]:
### elementy wise miltiplication [hadamard product]
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [65]:
# however for doing dot.product the inner value of the shapes need to match 
# as in case of matrix multiplication
np.dot( mat1.T , mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [66]:
mat1.T.shape , mat2.shape

((3, 5), (5, 3))

In [67]:
#since the inner values match i.e. 5 so dot product is possible 
# and the shape of the result will be 3,3 i.e. the outer numbers of the shapes

<h1>6. Dot product example [nut butter sales]</h1>

### there we have 2 dataframes .1. weekly sales data 2. item price
### our goal is to calculate the total sales value using the dot product

In [68]:
np.random.seed(0)

#number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [69]:
# creating weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amounts, 
                            index = ["Mon", "Tues", "Wed","Thurs","Friday"],
                           columns = ["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thurs               4              6             12
Friday              1              6              7

In [70]:
# creating prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [71]:
#now creating butter_prices dataframe from the numpy array
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Prices"], columns = ["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [72]:
## the below statement when execute give ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)
#total_sales = prices.dot(sales_amounts)

In [73]:
# shapes are not alinged lets transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [74]:
# create daily sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [75]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Friday
Prices  240   138  458    232     142

In [76]:
# now we want to append this daily_sales as a column to our weekly sales dataframe

weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon                12             15              0
Tues                3              3              7
Wed                 9             19             18
Thurs               4              6             12
Friday              1              6              7

In [77]:
## doesnt work since not the right shape
#weekly_sales["Total ($)"] = daily_sales


weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon                12             15              0        240
Tues                3              3              7        138
Wed                 9             19             18        458
Thurs               4              6             12        232
Friday              1              6              7        142

<h1> 7. Comparison operators</h1>

In [78]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [81]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [82]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [83]:
a1 < 5

array([ True,  True,  True])

In [84]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

<h1> 8.Sorting arrays</h1>

In [85]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [86]:
random_array.shape

(3, 5)

In [87]:
# the np.sort function returns a sorted copy of the original array.
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [88]:
# data in the original array still continue to remain the same
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [89]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [90]:
a1

array([1, 2, 3])

In [91]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [92]:
np.argmin(a1)

0

In [93]:
np.argmax(a1)

2

In [94]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0], dtype=int64)

In [95]:
np.argmax(random_array, axis=1)

array([4, 1, 1], dtype=int64)

<h1>9. practical example - Turn images into numpy array</h1>

<img src="numpy-images/panda.png"/>

In [96]:
# Turn an image into a NumPy array
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [97]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [98]:
panda.ndim , panda.shape, panda.size

(3, (2330, 3500, 3), 24465000)